
console.log("Hello Shanto");// To print 

let salarey = 20000 //let use only one time in one variable name 
console.log(salarey);

let newCourse = 200
let gst = 36
total = newCourse + gst
 console.log("Final amount of course:- ",total);

 let pwdsa =500
 console.log( "final course price of dsa  ",pwdsa + gst);

 console.log("Reminder answer is ", 2 % 5);//modulo give reminder 
 console.log(3**2);//3 ki power 2 

 let value1 = true
 
